const leagues = [
  {
    league: "Premier League",
    teams: [
      "Arsenal", "Aston Villa", "Bournemouth", "Brentford", "Brighton & Hove Albion", "Burnley", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Leeds United", "Liverpool", "Manchester City", "Manchester United", "Newcastle United", "Nottingham Forest", "Sunderland", "Tottenham Hotspur", "West Ham United", "Wolverhampton Wanderers",
    ],
  },
  {
    league: "La Liga",
    teams: [
      "Alavés", "Athletic Bilbao", "Atlético Madrid", "Barcelona", "Celta Vigo", "Elche", "Espanyol", "Getafe", "Girona", "Levante", "Mallorca", "Osasuna", "Rayo Vallecano", "Real Betis", "Real Oviedo", "Real Madrid", "Real Sociedad", "Sevilla", "Valencia", "Villarreal",
    ],
  },
  {
    league: "Bundesliga",
    teams: [
      "FC Augsburg", "Bayer 04 Leverkusen", "FC Bayern München", "SV Werder Bremen", "Borussia Dortmund", "Eintracht Frankfurt", "SC Freiburg", "Hamburger SV", "1. FC Heidenheim 1846", "TSG Hoffenheim", "1. FC Köln", "RB Leipzig", "1. FSV Mainz 05", "Borussia Mönchengladbach", "FC St. Pauli", "VfB Stuttgart", "1. FC Union Berlin", "VfL Wolfsburg",
    ],
  },
  {
    league: "Serie A",
    teams: [
      "Atalanta", "Bologna", "Cagliari", "Como", "Cremonese", "Fiorentina", "Genoa", "Hellas Verona", "Inter Milan", "Juventus", "Lazio", "Lecce", "AC Milan", "Napoli", "Parma", "Pisa",  "Roma", "Sassuolo", "Torino", "Udinese",
    ],
  },
  {
    league: "Ligue 1",
    teams: [
      "Auxerre", "Brest", "Lens", "Lille", "FC Lorient", "Lyon", "Marseille", "Monaco", "Montpellier", "Nantes", "Nice", "Paris FC", "Paris Saint-Germain", "Reims", "Rennes", "Saint-Étienne", "Strasbourg", "Toulouse",
    ],
  },
];

const teamData = {
    // Premier League
    "Arsenal": 57,
    "Aston Villa": 58,
    "Bournemouth": 1044,
    "Brentford": 402,
    "Brighton & Hove Albion": 397,
    "Burnley": 328,
    "Chelsea": 61,
    "Crystal Palace": 354,
    "Everton": 62,
    "Fulham": 63,
    "Leeds United": 341,
    "Liverpool": 64,
    "Manchester City": 65,
    "Manchester United": 66,
    "Newcastle United": 67,
    "Nottingham Forest": 351,
    "Sunderland": 71,
    "Tottenham Hotspur": 73,
    "West Ham United": 563,
    "Wolverhampton Wanderers": 76,

    // La Liga
    "Alavés": 263,
    "Athletic Bilbao": 77,
    "Atlético Madrid": 78,
    "Barcelona": 81,
    "Celta Vigo": 558,
    "Elche": 285,
    "Espanyol": 80,
    "Getafe": 82,
    "Girona": 298,
    "Levante": 88,
    "Mallorca": 89,
    "Osasuna": 79,
    "Rayo Vallecano": 87,
    "Real Betis": 90,
    "Real Madrid": 86,
    "Real Oviendo": 1048,
    "Real Sociedad": 92,
    "Sevilla": 559,
    "Valencia": 95,
    "Villarreal": 94,

    // Bundesliga
    "FC Augsburg": 16,
    "Bayer 04 Leverkusen": 3,
    "FC Bayern München": 5,
    "SV Werder Bremen": 12,
    "Borussia Dortmund": 4,
    "Eintracht Frankfurt": 19,
    "SC Freiburg": 17,
    "Hamburger SV": 7,
    "1. FC Heidenheim 1846": 44,
    "TSG Hoffenheim": 2,
    "1. FC Köln": 1,
    "RB Leipzig": 721,
    "1. FSV Mainz 05": 15,
    "Borussia Mönchengladbach": 18,
    "FC St. Pauli": 20, 
    "VfB Stuttgart": 10,
    "1. FC Union Berlin": 28,
    "VfL Wolfsburg": 11,

    // Serie A
    "Atalanta": 102,
    "Bologna": 103,
    "Cagliari": 104,
    "Como": 0,
    "Cremonese": 0, 
    "Fiorentina": 99,
    "Genoa": 107,
    "Hellas Verona": 0,
    "Inter Milan": 108,
    "Juventus": 109,
    "Lazio": 110,
    "Lecce": 0,
    "AC Milan": 98,
    "Napoli": 113,
    "Parma": 112,
    "Pisa": 0,
    "Roma": 100,
    "Sassuolo": 0, 
    "Torino": 0,
    "Udinese": 115,

    // Ligue 1
    "Auxerre": 519,
    "Brest": 512,
    "Lens": 546,
    "Lille": 521,
    "FC Lorient": 525,
    "Lyon": 523,
    "Marseille": 516,
    "Monaco": 548,
    "Nantes": 543,
    "Nice": 522,
    "Paris FC": 1045,
    "Paris Saint-Germain": 524,
    "Rennes": 0,
    "Saint-Étienne": 0,
    "Strasbourg": 576,
    "Toulouse": 511,
};